version: '3'
services:
  xserver:
    image: ghcr.io/ihelal-org/docker-xserver:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20

  simulator:
    image: robot-sim:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:0
      # Add ROS_MASTER_URI environment variable pointing to itself
      - ROS_MASTER_URI=http://simulator:11311
    volumes_from:
      - xserver
    depends_on:
      - xserver

  workspace:
    image: ros-dev:latest
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3001:3000"
      - "3002:8888"
    volumes:
      - workspace:/workspace
    environment:
      - DISPLAY=:0
      # Ensure this points to the ROS master in the simulator container
      - ROS_MASTER_URI=http://simulator:11311/
    volumes_from:
      - xserver
      - simulator
    depends_on:
      - xserver
      - simulator  # Ensure workspace waits for simulator to start

volumes:
  workspace:
