version: '2.3'
services:
  xserver:
    image: ghcr.io/ihelal-org/docker-xserver:latest
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20
  # TODO: Skip for now but come back to this to have sim in the env
  simulator:
    image: ghcr.io/ihelal-org/ros-devcontainer-vscode:latest
    ipc: host
    security_opt:
    - seccomp:unconfined
    environment:
    - DISPLAY=:0
    volumes_from:
    - xserver
    depends_on:
    - xserver
  workspace:
    # env_file:
    #   - .env
    image: ghcr.io/ihelal-org/ros-devcontainer-vscode:latest
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3001:3000"
    - "3002:8888"
    volumes:
    - workspace:/workspace
    environment:
    - DISPLAY=:0
    - ROS_MASTER_URI=http://simulator:11311/
    volumes_from:
    - xserver
    - simulator
    depends_on:
    - xserver
volumes:
  workspace:
