name: Docker Image Push to GHCR

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  push:
    name: Push Docker Image to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}' | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$REPO_NAME
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            docker build . --tag $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:$TAG
          fi
          
          docker build . --tag $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
